server:
  contextPath: /

logging:
  level:
    dentistq: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

spring:
  profiles:
    active: "devMySQL_vh"

dentistq:
  token:
    header: "X-Auth-Token"

---


spring:
  profiles: devPostgre
  datasource:
    url: jdbc:postgresql://localhost:5432/ft
    driver-class-name: org.postgresql.Driver
    username: romm
    password: romm
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgresPlusDialect
    
---


spring:
  profiles: devMySQL_vh
  datasource:
    url: jdbc:mysql://localhost:3306/ttq_db?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect


---


spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect